version: '3.8'

services:
  backend:
    image: localhost:5000/backend:latest
    container_name: backend_container
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: localhost:5000/frontend:latest
    container_name: frontend_container
    ports:
      - "3000:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
