version: '3.8'

services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  backend:
    image: localhost:5000/backend:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db-master
      - db-slave
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-master:3306/etudiants_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: asma1234


  frontend:
    image: localhost:5000/frontend:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:80"
    networks:
      - app-network

  db-master:
    image: mysql:8.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asma1234
      MYSQL_DATABASE: etudiants_db
      MYSQL_REPLICATION_MODE: master
    volumes:
      - mysql-master-data:/var/lib/mysql
    networks:
      - app-network
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=etudiants_db
      --gtid-mode=ON
      --enforce-gtid-consistency=TRUE
      --log-slave-updates=TRUE

  db-slave:
    image: mysql:8.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asma1234
      MYSQL_DATABASE: etudiants_db            
      MYSQL_MASTER_PASSWORD: asma1234
      MYSQL_REPLICATION_MODE: slave
      MYSQL_MASTER_HOST: db-master
      MYSQL_MASTER_PORT: 3306
    volumes:
      - mysql-slave-data:/var/lib/mysql
    networks:
      - app-network
    depends_on:
      - db-master
    command: >
      --server-id=2
      --log-bin=mysql-bin
      --gtid-mode=ON
      --enforce-gtid-consistency=TRUE
      --read-only=TRUE

networks:
  app-network:
    driver: overlay

volumes:
  mysql-master-data:
    driver: local
  mysql-slave-data:
    driver: local

