apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: exam
spec:
  hard:
    requests.cpu: "4"        
    requests.memory: "8Gi"    
    limits.cpu: "4"           
    limits.memory: "8Gi"     
