apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exam-role
  namespace: exam
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exam-role-binding
  namespace: exam
subjects:
- kind: ServiceAccount
  name: default
  namespace: exam
roleRef:
  kind: Role
  name: exam-role           
  apiGroup: rbac.authorization.k8s.io


